### PR TITLE
[DEV APPROVED] Moving the shared MAS SCSS modules into Yeast

### PR DESCRIPTION
**Pull request by slaywell**
## Why?

As we have built more and more free-standing tools (RAD, CIA, Universal Credit) that need MAS branding we have the need for some generic MAS branded styles. A quick way of doing this was simply linking to the main MAS site CSS file, but this has caused issues when we migrated servers, is harder to maintain, and is not good for frontend performance.

## What?

Yeast is currently a source for SCSS **mixins** and **variables** that are used across projects. It does not output any of its own CSS after being compiled.

This PR moves SCSS components from Frontend into Yeast. These components are in four categories:

- Helpers - some extra mixins that are required
- Base - default HTML element styling
- Layout - large, common page layout options such as columns, headers, footers
- Components - reusable page modules. At the moment this only includes the Dough Theme folder which is how MAS branding is applied to Dough components. We may find that more files are necessary in this folder

### Frontend (MAS Website)
An accompanying change will need to be made to Frontend so that these shared components are removed, and the SCSS file points at Yeast.
Since this is all compiled within the main `_enhanced.scss` file and loaded as a single CSS file by the site, this should not cause any specificity problems as the CSS that is outputted will be exactly the same.

### RAD, CIA
These will be unaffected, but should be refactored to use the new components in Yeast and have the hard-coded references to the main site CSS removed.

### Ongoing CSS development
When we change MAS CSS we will need to consider if it's project-specific, or global. Any global changes (e.g. the site header, the main MAS colours) will need to be made in Yeast and checked across all projects. Any project-specific ones will be made within the individual project only.

### CODE REVIEW

**Comment by munckymagik** [comment]
Yes yes yes. This is what we need. Thank you 👍

**Comment by spencer** [comment]
👍 Awesome

**Comment by davidtrussler** [comment]
👍 Excellent.

**Comment by jongilbraith** [comment]
Great stuff 👍

**Comment by oneKelvinSmith** [comment]
👍 Very cool.

**Pull request merged**
